# technologien.py

TECHNOLOGIEN = (
    "Unsere KI-Agenten basieren auf einer leistungsstarken, sicheren und skalierbaren Technologieplattform.\n\n"
    "☁️oderne Cloud-Ökosysteme\n"
    "Wir entwickeln, deployen und betreiben KI-Agenten in allen führenden Cloud-Umgebungen:\n"
    "- Microsoft Azure – Enterprise-Security, AD-Integration, Azure ML, Data Factory\n"
    "- Amazon AWS – Skalierbare KI-Workloads, Lambda, S3, SageMaker\n"
    "- Google Cloud (GCP) – BigQuery, Vertex AI, effizientes Modell-Hosting\n\n"
    " Datenschutz & sensible Daten\n"
    "Viele Kunden arbeiten mit hochsensiblen Informationen. Dafür bieten wir:\n"
    "- DSGVO-konforme Datenverarbeitung\n"
    "- Verschlüsselte End-to-End-Datenpipelines\n"
    "- On-Premise- oder Private-Cloud-Deployments\n"
    "- Zugriffsbeschränkungen & Zero-Trust-Architekturen\n"
    "- Isolierte Mandantenumgebungen für maximale Sicherheit\n\n"
    " KI-Agenten beim Kunden – maßgeschneidert & begleitet\n"
    "Wir entwickeln KI-Agenten individuell für Ihr Unternehmen und unterstützen Sie bei jeder Phase:\n"
    "- Analyse der bestehenden Prozesse\n"
    "- Aufbau der passenden Agenten-Crew\n"
    "- Integration in CRM, ERP, Data Warehouse oder operative Systeme\n"
    "- Begleitung Ihres Teams bis zum produktiven Betrieb\n\n"
    " KI-Agenten auch ohne eigenes Data-Team\n"
    "Viele Unternehmen haben kein Data- oder AI-Team. Kein Problem.\n"
    "Mit unserem Abo-Modell erhalten Sie:\n"
    "- Sofort einsatzbereite Agenten\n"
    "- Regelmäßige Modell-Updates\n"
    "- Betreuung, Monitoring & Support\n"
    "- Skalierbare Nutzung nach Bedarf\n\n"
    "  Warum unsere Technologie überzeugt\n"
    "- Hochgradige Automatisierung Ihrer Prozesse\n"
    "- Skalierbare KI-Architektur für schnelles Wachstum\n"
    "- Maximale Sicherheit für sensible Daten\n"
    "- Flexible Deployment-Optionen (Cloud, Hybrid, On-Premise)\n"
    "- Vollservice von der Analyse bis zum Betrieb\n\n"
    "Unsere Technologie stellt sicher: Sie erhalten nicht nur Agenten – Sie erhalten funktionierende, nachhaltige KI-Lösungen, die echten Mehrwert schaffen."
)
